### ISSUE TITLE
Fix exports

### ISSUE THREAD

**Issue by cheater** [chrisnc/hvx#8]
I have a function such as this:
```
varsAsVect xs = vOut
  -- takes a list of variables and outputs them as a single vector Expr
  where
    n = length xs
    zeros = [0, 0..] :: [Double]
    vOut = foldl' (+~) (head vs) (tail vs)
    unitListAtIndex :: Int -> [Double]
    unitListAtIndex ind
      -- creates a list with 0s except for 1 at index ind
      | ind < 0 = undefined
      | ind == 0 = 1 : zeros
      | otherwise = 0 : (unitListAtIndex (ind - 1))

    unitVectAtIndex :: Int -> Matrix Double
    unitVectAtIndex i = (n><1) (unitListAtIndex i)

    xsIndices = zip ([0..] :: [Int]) xs
    vs = f <$> xsIndices
      where
        f (ind, x) = v *~ x
          where v = EConst $ unitVectAtIndex ind
```
This is typed by GHC as:
```
varsAsVect
  :: HVX.Internal.DCP.ValidVex
       (HVX.Internal.DCP.ApplyVex
          'HVX.Internal.DCP.Affine 'HVX.Internal.DCP.Nonmon v1 m1) =>
     [HVX.Internal.Primitives.Expr v1 m1]
     -> HVX.Internal.Primitives.Expr
          (HVX.Internal.DCP.ApplyVex
             'HVX.Internal.DCP.Affine 'HVX.Internal.DCP.Nonmon v1 m1)
          (HVX.Internal.DCP.ApplyMon 'HVX.Internal.DCP.Nonmon m1)
```
I need to have the ability to write out this type and other similar types for a type signature. However, I cannot import from `HVX.Internal.*` in code using hvx as an external library.

In #4 you mention that one should not export `ValidVex` or `ApplyVex` but I didn't understand the reasoning. Would you be nice enough to look into this, please? Also could you try to explain again why they shouldn't be re-exported? I would like to understand this as well.

**Comment by chrisnc** [comment]
This is a reasonable use-case, but my reasoning for the comment was that these kinds of functions likely belong inside the library. In this specific case, the concatenation of several variables should remain monotonic with respect to each variable, but as you can see from the type, this is not what DCP infers. As such, this is unlikely to be a very useful function in a convex optimization problem because its convexity and monotonicity properties totally disappear. Also, from the type, this function only type-checks if each element of the list has the same convexity and monotonicity. A much more useful implementation of this function would be able to assert properties of convexity and monotonicity outside of DCP, but this ability to just assert convexity and monotonicity properties breaks the abstraction that the library provides.

**Comment by cheater** [comment]
Would you mind coming on irc or talking the details of this through over email? There are some questiobs not directly related to this that I wanted to ask to figure a solution.

**Comment by cheater** [comment]
In specific, I didn't fully understand your comment that "this is unlikely to be a very useful function in a convex optimization problem because its convexity and monotonicity properties totally disappear" - so I was wondering if you could explain your train of thought to me? We can continue here as well.

**Comment by chrisnc** [comment]
My previous comment already says this, but I'll try to rephrase: writing the function in the way that you have will result in expressions that have less useful convexity and monotonicity properties than if you wrote it in a way where those properties were determined outside of the DCP framework and then asserted by the library. Similarly to how the quadratic form primitive, if written manually as two multiplications, would not have the useful convexity property that a quadratic form actually has.

Exposing the ability construct expressions that _assert_ their convexity properties, rather than _derive_ them with DCP, breaks the abstraction barrier that the library is meant to provide, which is why the parts of the library that support this ability are confined to the `HVX.Internal.*` module namespace. You can import them if you want, but the reason you would do so is to write new primitives that have the same power and capabilities as the ones that are in the library.

**Comment by cheater** [comment]
Thanks for the longer explanation. What does "less useful" mean in this case? Does it mean the solver won't be able to solve the system?

**Comment by chrisnc** [comment]
It means that you will be able to use such an expression in fewer, if any, places within a convex problem. The objective expression needs to be convex, and the constraints need to be convex as well. Forms with less-determined convexity and monotonicity than what they should have make using them much harder, if not impossible.

**Comment by cheater** [comment]
Oh, I didn't realize the objective needed to be convex. So how would I use this sort of thing in an objective, then? I need to find the distance between this vector (a concatenation of variables) and a line in R^n (n being the amount of variables) defined by a constant vector; the objective is to minimize that distance.

I could add this function (vector concatenation) to hvx, but I'm not sure how to ensure the properties you talk about.

**Comment by cheater** [comment]
Just wanted to mention that my linear algebra is OK, but I don't know what the definition of convexity would be here, so if you could explain this a little, that would help a lot.

**Comment by chrisnc** [comment]
The definition on wikipedia is pretty concise. You should also take a look at the DCP docs. The first few paragraphs of that tutorial give another good example of the phenomenon I was describing in this thread (forming convex expressions that DCP cannot certify as convex).

https://en.wikipedia.org/wiki/Convex_function#Definition
http://cvxr.com/cvx/doc/dcp.html

**Comment by cheater** [comment]
OK, I read those links, good refresher. I didn't realize the second link existed, good read.

So I could add the function to hvx, but there are two issues

1. the function is both concave and convex because it is linear. It seems neither hvx nor the DCP docs even consider this possibility. The types in hvx would need to be expanded, or we'd need to add two versions of the function

2. if every time you need to use a function that hvx can't properly figure out the convexity of, that's a big issue, because there's a lot of functions that are non-obvious like this. I suggest instead doing something like `unsafeTrustCurvature` which will let people just define functions with their real curvature; I think that it is better to trust the programmer than disable him completely. The con is a person who uses this function without thinking things through will run into problems by breaking DCP assumptions. However, `unsafeTrustCurvature` should be well documented for what it is, and it should explicitly be said that the function must have the curvature declared here. What do you think? Eventually, maybe a QuickCheck based function could be used to automatically classify the curvature for someone who isn't certain of it.

**Comment by cheater** [comment]
Regarding 2. I understand you can import stuff from HVX.Internal.* but that seems like digging too deep. I think there should be a preferred way to do this sort of thing, that's why I suggested something like this.

**Comment by chrisnc** [comment]
> 1. the function is both concave and convex because it is linear. It seems neither hvx nor the DCP docs even consider this possibility. The types in hvx would need to be expanded, or we'd need to add two versions of the function

It's really difficult to have a productive discussion about this without having a common base of knowledge about convex analysis. A function which is both convex and concave is an affine function, and this is absolutely accounted for in DCP and HVX (and CVX and all other implementations of this idea).

The problem with something like `unsafeTrustCurvature` is that you still need to define the function in a way that HVX can use, which includes defining how to evaluate it and take its subgradient, which is by far the more involved part of adding a new primitive. Also, the word `unsafe` is really quite confusing in this context, and doesn't capture at all what you're trying to do. I want to keep the structure and scope of this library to be basically the same as CVX/CVXPY, which use this same barrier of primitives mostly defined in the library, but with the ability to reach in and define new ones available for experts.

**Comment by cheater** [comment]
Thanks for the pointers
